In [ ]:
import pandas as pd
import numpy as np
import datetime

In [ ]:
inside = pd.read_excel('Bus_DataBase_Inside.xlsx')

In [ ]:
inside.head()

,Station,Bus arrival time,Opening the doors,Closing the doors,Number of entries,Number of exits,Bus movement,position,Date
0,خاوران,06:40:14,06:40:18,06:41:55,22,0,06:41:58,جنوب به شمال,شنبه
1,بسیج,06:46:17,06:46:30,06:46:43,13,0,06:46:43,جنوب به شمال,شنبه
2,رحمانی,06:47:09,06:47:16,06:47:25,12,0,06:47:29,جنوب به شمال,شنبه
3,ولیعصر,06:48:47,06:48:49,06:49:10,1,1,06:49:12,جنوب به شمال,شنبه
4,خاوران,06:59:43,06:59:47,07:02:56,51,0,07:03:02,جنوب به شمال,شنبه

In [ ]:
station = pd.read_excel('Bus_DataBase_Station.xlsx')

In [ ]:
station.head()

,Station,Bus arrival time,Opening the doors,Closing the doors,Number of entries,Number of exits,Bus movement,missed the bus,position,Date
0,خاوران,07:36:59,07:37:05,07:37:20,0,34,07:37:28,0,شمال به جنوب,شنبه
1,خاوران,07:40:00,07:40:21,07:40:43,0,15,07:40:47,0,شمال به جنوب,شنبه
2,خاوران,07:43:23,07:43:27,07:44:55,0,34,07:45:02,0,شمال به جنوب,شنبه
3,خاوران,07:49:08,07:49:12,07:49:26,0,26,07:49:29,0,شمال به جنوب,شنبه
4,خاوران,07:49:35,07:49:39,07:49:49,0,8,07:49:53,0,شمال به جنوب,شنبه

In [ ]:
print(inside.shape)

(145, 9)

In [ ]:
today = datetime.date.today()
counter = 0
for index, row in station.iterrows():
    for i, j in inside.iterrows():
      if (row['Station'] == j['Station']) and (row['position'] == j['position']) and (row['Date'] == j['Date']):
        diff = datetime.datetime(1300,1,1)
        s_date = datetime.datetime.combine(today, row['Bus arrival time'])
        i_date = datetime.datetime.combine(today, j['Bus arrival time'])
        if row['Bus arrival time'] > j['Bus arrival time']:
          diff = s_date - i_date
        else:
          diff = i_date - s_date

        if diff.total_seconds() < 60:
          counter += 1
          inside.drop(i,inplace=True)
print(counter)

20

In [ ]:
station.columns

Index(['Station', 'Bus arrival time', 'Opening the doors', 'Closing the doors',
       'Number of entries', 'Number of exits', 'Bus movement',
       'missed the bus', 'position', 'Date'],
      dtype='object')

In [ ]:
print(inside.shape)

(125, 9)

In [ ]:
station.columns

Index(['Station', 'Bus arrival time', 'Opening the doors', 'Closing the doors',
       'Number of entries', 'Number of exits', 'Bus movement',
       'missed the bus', 'position', 'Date'],
      dtype='object')

In [ ]:
station.drop(['missed the bus'], axis=1, inplace=True)

In [ ]:
station.columns

Index(['Station', 'Bus arrival time', 'Opening the doors', 'Closing the doors',
       'Number of entries', 'Number of exits', 'Bus movement', 'position',
       'Date'],
      dtype='object')

In [ ]:
out = pd.concat([inside, station], ignore_index= True)

In [ ]:
out.head()

,Station,Bus arrival time,Opening the doors,Closing the doors,Number of entries,Number of exits,Bus movement,position,Date
0,خاوران,06:40:14,06:40:18,06:41:55,22,0,06:41:58,جنوب به شمال,شنبه
1,بسیج,06:46:17,06:46:30,06:46:43,13,0,06:46:43,جنوب به شمال,شنبه
2,رحمانی,06:47:09,06:47:16,06:47:25,12,0,06:47:29,جنوب به شمال,شنبه
3,ولیعصر,06:48:47,06:48:49,06:49:10,1,1,06:49:12,جنوب به شمال,شنبه
4,رحمانی,07:09:33,07:09:38,07:09:48,7,4,07:09:55,جنوب به شمال,شنبه

In [ ]:
out.shape

(321, 9)

In [ ]:
out.to_excel('output.xlsx', index = False)